import { db } from "@workspace/db";
import {
  categoriesTable, clubsTable, restaurantsTable, toursTable,
  productsTable, eventsTable, promotionsTable,
} from "@workspace/db/schema";

async function seed() {
  console.log("Seeding SA PLUG database...");

  // Categories
  const cats = await db.insert(categoriesTable).values([
    { name: "Clubs", icon: "music", order: 1, active: true },
    { name: "Restaurants", icon: "utensils", order: 2, active: true },
    { name: "Tours", icon: "map", order: 3, active: true },
    { name: "Products", icon: "shopping-bag", order: 4, active: true },
    { name: "Events", icon: "calendar", order: 5, active: true },
    { name: "VIP Experiences", icon: "star", order: 6, active: true },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${cats.length} categories`);

  const clubCatId = 1;
  const restCatId = 2;
  const tourCatId = 3;
  const prodCatId = 4;
  const eventCatId = 5;

  // Clubs
  const clubs = await db.insert(clubsTable).values([
    {
      name: "Taboo",
      description: "Joburg's most exclusive nightclub. World-class DJs, premium bottle service, and a strictly curated guest list make Taboo the pinnacle of SA nightlife.",
      images: ["https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800", "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800"],
      price: "500",
      address: "Nelson Mandela Square, Sandton, Johannesburg",
      phone: "+27 11 883 0000",
      contactEmail: "bookings@taboo.co.za",
      dressCode: "Smart Casual to Formal — No sneakers, no shorts",
      openingHours: "Thu–Sat: 21:00–05:00",
      minSpend: "500",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["vip", "bottle service", "dj", "sandton"],
      categoryId: clubCatId,
    },
    {
      name: "Konka",
      description: "Cape Town's hottest Afro-soul venue. Konka blends rich South African culture with premium entertainment — from kwaito to Amapiano, every night is a celebration.",
      images: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800", "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800"],
      price: "350",
      address: "Woodstock, Cape Town",
      phone: "+27 21 447 0000",
      contactEmail: "events@konka.co.za",
      dressCode: "Smart Casual — Afrocentric dress welcomed",
      openingHours: "Fri–Sun: 20:00–04:00",
      minSpend: "350",
      isTrending: true,
      isFeatured: false,
      isPopular: true,
      available: true,
      tags: ["amapiano", "afrosoul", "cape town", "culture"],
      categoryId: clubCatId,
    },
    {
      name: "Ayepyep Lifestyle",
      description: "Pretoria's premier upscale lounge and club experience. Ayepyep brings together the finest sounds, cuisine and cocktails in a beautifully designed space.",
      images: ["https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800"],
      price: "300",
      address: "Arcadia, Pretoria",
      phone: "+27 12 344 0000",
      contactEmail: "info@ayepyep.co.za",
      dressCode: "Smart Casual",
      openingHours: "Wed–Sun: 19:00–03:00",
      minSpend: "300",
      isTrending: false,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["pretoria", "lounge", "cocktails"],
      categoryId: clubCatId,
    },
    {
      name: "The Orbit",
      description: "Johannesburg's premier jazz and world music club. The Orbit brings together South Africa's finest jazz musicians in an intimate atmosphere with great food and cocktails.",
      images: ["https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800"],
      price: "200",
      address: "Braamfontein, Johannesburg",
      phone: "+27 11 403 0000",
      contactEmail: "bookings@theorbit.co.za",
      dressCode: "Smart Casual",
      openingHours: "Tue–Sat: 19:00–02:00",
      minSpend: "200",
      isTrending: false,
      isFeatured: false,
      isPopular: true,
      available: true,
      tags: ["jazz", "live music", "braamfontein"],
      categoryId: clubCatId,
    },
    {
      name: "Truth Coffee Roasting",
      description: "Not just a coffee shop — Cape Town's legendary steampunk cathedral. By night, Truth transforms into a premium cocktail bar with live music and an unmatched atmosphere.",
      images: ["https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800"],
      price: "150",
      address: "36 Buitenkant St, Cape Town",
      phone: "+27 21 200 0440",
      contactEmail: "hello@truth.co.za",
      dressCode: "Casual",
      openingHours: "Mon–Sun: 07:00–23:00",
      minSpend: "150",
      isTrending: false,
      isFeatured: true,
      isPopular: false,
      available: true,
      tags: ["cape town", "cocktails", "steampunk", "live music"],
      categoryId: clubCatId,
    },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${clubs.length} clubs`);

  // Restaurants
  const restaurants = await db.insert(restaurantsTable).values([
    {
      name: "The Pot Luck Club",
      description: "Chef Luke Dale-Roberts' iconic tapas restaurant atop The Old Biscuit Mill. Extraordinary small plates, breathtaking views, and an electric atmosphere in Cape Town.",
      images: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800"],
      price: "800",
      address: "The Old Biscuit Mill, 375 Albert Rd, Woodstock, Cape Town",
      phone: "+27 21 447 0804",
      contactEmail: "reservations@thepotluckclub.co.za",
      cuisine: "Contemporary Fine Dining / Tapas",
      openingHours: "Tue–Sat: 12:00–15:00, 18:30–22:30",
      dressCode: "Smart Casual",
      reservationRequired: true,
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["fine dining", "cape town", "tapas", "rooftop"],
      categoryId: restCatId,
    },
    {
      name: "Marble Restaurant",
      description: "Joburg's most celebrated open-fire restaurant. Chef David Higgs' wood-fired masterpieces and the iconic Marble bar make this a must-visit Sandton institution.",
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800"],
      price: "900",
      address: "Corner Keyes & Sturdee Ave, Rosebank, Johannesburg",
      phone: "+27 11 327 7970",
      contactEmail: "eat@marble.co.za",
      cuisine: "Open-Fire Contemporary",
      openingHours: "Mon–Sun: 12:00–15:00, 18:00–22:30",
      dressCode: "Smart Casual to Formal",
      reservationRequired: true,
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["joburg", "fire", "fine dining", "rosebank"],
      categoryId: restCatId,
    },
    {
      name: "Nando's",
      description: "South Africa's iconic flame-grilled peri-peri chicken restaurant. Born in Johannesburg in 1987, Nando's is a beloved SA institution with bold flavours and vibrant art.",
      images: ["https://images.unsplash.com/photo-1562967915-6ba607ff7d05?w=800"],
      price: "180",
      address: "Multiple locations nationwide",
      phone: "+27 11 000 0000",
      contactEmail: "info@nandos.co.za",
      cuisine: "Peri-Peri / Flame Grilled",
      openingHours: "Mon–Sun: 11:00–22:00",
      dressCode: "Casual",
      reservationRequired: false,
      isTrending: false,
      isFeatured: false,
      isPopular: true,
      available: true,
      tags: ["peri-peri", "chicken", "casual", "nationwide"],
      categoryId: restCatId,
    },
    {
      name: "Wolfgat",
      description: "World-renowned foraging restaurant on the West Coast. Chef Kobus van der Merwe creates extraordinary tasting menus from locally foraged and fished ingredients.",
      images: ["https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800"],
      price: "1200",
      address: "1 Beach Rd, Paternoster, Western Cape",
      phone: "+27 22 752 2038",
      contactEmail: "hello@wolfgat.co.za",
      cuisine: "Foraging / West Coast",
      openingHours: "Wed–Sun: 12:00–15:00 (tasting menu only)",
      dressCode: "Casual Beach Chic",
      reservationRequired: true,
      isTrending: true,
      isFeatured: true,
      isPopular: false,
      available: true,
      tags: ["foraging", "tasting menu", "west coast", "luxury"],
      categoryId: restCatId,
    },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${restaurants.length} restaurants`);

  // Tours
  const tours = await db.insert(toursTable).values([
    {
      name: "Soweto Heritage & Nightlife Tour",
      description: "Experience the soul of South Africa in Soweto. Visit Vilakazi Street, the Hector Pieterson Museum, Nelson Mandela's former home, and end the evening at a legendary shebeen with live jazz.",
      images: ["https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800", "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800"],
      price: "1200",
      address: "Pickup: Sandton City, Johannesburg",
      phone: "+27 11 000 0000",
      contactEmail: "tours@saplug.co.za",
      duration: "8 hours",
      includes: ["Transport", "Guided tour", "Museum entry", "Traditional dinner", "Shebeen experience"],
      maxGroupSize: 12,
      meetingPoint: "Sandton City Main Entrance",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["soweto", "heritage", "culture", "nightlife"],
      categoryId: tourCatId,
    },
    {
      name: "Cape Peninsula Sunset Experience",
      description: "A full-day luxury tour of the Cape Peninsula. Chapman's Peak Drive, Cape Point, Boulder's Beach penguins, and a sunset wine tasting at a Constantia vineyard.",
      images: ["https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800"],
      price: "1800",
      address: "Pickup: Cape Town Waterfront",
      phone: "+27 21 000 0000",
      contactEmail: "capetours@saplug.co.za",
      duration: "Full day (10 hours)",
      includes: ["Luxury transport", "Park entry fees", "Wine tasting (3 wines)", "Gourmet picnic lunch", "Penguin colony visit"],
      maxGroupSize: 8,
      meetingPoint: "V&A Waterfront Clock Tower",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["cape town", "peninsula", "wine", "luxury", "penguins"],
      categoryId: tourCatId,
    },
    {
      name: "Joburg Art Deco & Street Art Walk",
      description: "Discover Johannesburg's vibrant urban culture. Explore Maboneng Precinct, Arts on Main, and meet local artists in this curated 3-hour walking tour.",
      images: ["https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800"],
      price: "450",
      address: "Maboneng Precinct, Johannesburg",
      phone: "+27 11 000 0000",
      contactEmail: "arttours@saplug.co.za",
      duration: "3 hours",
      includes: ["Professional guide", "Gallery access", "Artist studio visit", "Welcome drink"],
      maxGroupSize: 15,
      meetingPoint: "Arts on Main Entrance, 264 Fox St",
      isTrending: false,
      isFeatured: true,
      isPopular: false,
      available: true,
      tags: ["art", "joburg", "walking tour", "culture"],
      categoryId: tourCatId,
    },
    {
      name: "Kruger Safari Day Trip",
      description: "Experience the Big 5 in the world-famous Kruger National Park. Expert ranger-guided game drive with breakfast in the bush and sundowner drinks at dusk.",
      images: ["https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800"],
      price: "3500",
      address: "Pickup: Johannesburg O.R. Tambo Airport",
      phone: "+27 13 000 0000",
      contactEmail: "safari@saplug.co.za",
      duration: "Full day (14 hours)",
      includes: ["Return transport", "Game drive x2", "Bush breakfast", "Sundowner drinks", "Ranger guide"],
      maxGroupSize: 6,
      meetingPoint: "O.R. Tambo International Airport",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["safari", "kruger", "big 5", "wildlife", "luxury"],
      categoryId: tourCatId,
    },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${tours.length} tours`);

  // Products
  const products = await db.insert(productsTable).values([
    {
      name: "SA PLUG VIP Membership Card",
      description: "The ultimate access pass. Annual VIP Membership gives you priority entry, exclusive discounts at partner venues, and concierge booking services.",
      images: ["https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800"],
      price: "2999",
      sku: "VIP-ANNUAL-001",
      stock: 500,
      brand: "SA PLUG",
      sizes: ["Standard"],
      colours: ["Gold"],
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["vip", "membership", "exclusive", "annual"],
      categoryId: prodCatId,
    },
    {
      name: "Premium Whisky Gift Set",
      description: "Curated South African premium whisky collection. Includes Bain's Cape Mountain Whisky, Three Ships Premium Select, and Andy Watts Finished in Sherry Casks. Beautifully gift-boxed.",
      images: ["https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800"],
      price: "1200",
      sku: "WHISKY-SET-001",
      stock: 50,
      brand: "SA Spirits Collection",
      sizes: ["3-Bottle Set"],
      colours: ["Premium Boxed"],
      isTrending: false,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["whisky", "gift", "south african", "premium"],
      categoryId: prodCatId,
    },
    {
      name: "SA PLUG Luxury Cap",
      description: "Premium embroidered cap in signature SA PLUG gold on black. Structured 6-panel, adjustable strap, UV protection. Limited edition.",
      images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800"],
      price: "450",
      sku: "CAP-GOLD-001",
      stock: 200,
      brand: "SA PLUG",
      sizes: ["One Size"],
      colours: ["Black/Gold"],
      isTrending: true,
      isFeatured: false,
      isPopular: true,
      available: true,
      tags: ["cap", "merch", "gold", "limited edition"],
      categoryId: prodCatId,
    },
    {
      name: "VIP Night Package — Couple",
      description: "The perfect date night. Includes two VIP tickets to your choice of partner club, a premium bottle of Moët & Chandon, and a private table reservation.",
      images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800"],
      price: "3500",
      sku: "VIP-COUPLE-001",
      stock: 20,
      brand: "SA PLUG",
      sizes: ["Couple (2 persons)"],
      colours: ["N/A"],
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["vip", "couple", "champagne", "date night"],
      categoryId: prodCatId,
    },
    {
      name: "Luxury Grooming Kit",
      description: "Premium men's grooming set. SA-crafted beard oil, shaving cream, moisturiser, and cologne — all in a bespoke leather travel case. The gentleman's essential.",
      images: ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800"],
      price: "850",
      sku: "GROOM-KIT-001",
      stock: 80,
      brand: "Gentleman SA",
      sizes: ["One Size"],
      colours: ["Leather Brown"],
      isTrending: false,
      isFeatured: true,
      isPopular: false,
      available: true,
      tags: ["grooming", "men", "luxury", "gift"],
      categoryId: prodCatId,
    },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${products.length} products`);

  // Events
  const events = await db.insert(eventsTable).values([
    {
      name: "Amapiano All White Affair",
      description: "SA PLUG's signature all-white Amapiano night. South Africa's hottest DJs, outdoor dance floor, premium bottle service and an unforgettable energy. White attire mandatory.",
      images: ["https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800", "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800"],
      price: "450",
      address: "Taboo, Nelson Mandela Square, Sandton",
      eventDate: "2026-07-19",
      eventTime: "21:00",
      venue: "Taboo Nightclub, Sandton",
      dressCode: "All White — Strictly Enforced",
      lineup: ["DJ Maphorisa", "Kabza De Small", "Uncle Waffles", "Ami Faku"],
      ticketUrl: "https://saplug.co.za/tickets/allwhite",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["amapiano", "all white", "sandton", "premium"],
      categoryId: eventCatId,
    },
    {
      name: "Rooftop Jazz Under the Stars",
      description: "An intimate evening of world-class jazz on Johannesburg's most exclusive rooftop. Cape jazz legends meet contemporary fusion in a setting above the city skyline.",
      images: ["https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800"],
      price: "350",
      address: "The Orbit, Braamfontein, Johannesburg",
      eventDate: "2026-07-26",
      eventTime: "19:00",
      venue: "The Orbit Rooftop, Braamfontein",
      dressCode: "Smart Casual",
      lineup: ["Kyle Shepherd Trio", "Nduduzo Makhathini", "Special Surprise Guest"],
      ticketUrl: "https://saplug.co.za/tickets/rooftopjazz",
      isTrending: false,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["jazz", "rooftop", "joburg", "live music"],
      categoryId: eventCatId,
    },
    {
      name: "Cape Town New Year's Eve Gala",
      description: "Celebrate New Year's Eve in style at Cape Town's most exclusive black-tie gala. Multi-course dinner, champagne toast, live entertainment and front-row fireworks views over the Waterfront.",
      images: ["https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800"],
      price: "2500",
      address: "One&Only Cape Town, V&A Waterfront",
      eventDate: "2026-12-31",
      eventTime: "18:30",
      venue: "One&Only Cape Town Ballroom",
      dressCode: "Black Tie — Formal",
      lineup: ["Freshlyground", "Lira", "Jonathan Butler", "DJ Fresh"],
      ticketUrl: "https://saplug.co.za/tickets/nye2026",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["nye", "gala", "cape town", "black tie", "champagne"],
      categoryId: eventCatId,
    },
    {
      name: "Durban Afrobeats Festival",
      description: "The biggest Afrobeats celebration on the East Coast. International acts, local artists, street food, and an ocean-view stage at Durban's iconic beachfront.",
      images: ["https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800"],
      price: "650",
      address: "Durban Beachfront, KwaZulu-Natal",
      eventDate: "2026-08-09",
      eventTime: "14:00",
      venue: "Durban Beachfront Amphitheatre",
      dressCode: "Casual — Beach Festival",
      lineup: ["Burna Boy", "Davido", "Focalistic", "Sha Sha"],
      ticketUrl: "https://saplug.co.za/tickets/afrobeats",
      isTrending: true,
      isFeatured: true,
      isPopular: true,
      available: true,
      tags: ["afrobeats", "festival", "durban", "international"],
      categoryId: eventCatId,
    },
  ]).onConflictDoNothing().returning();
  console.log(`✓ ${events.length} events`);

  // Promotions
  await db.insert(promotionsTable).values([
    {
      title: "Weekend VIP Special — 20% Off All Bookings",
      body: "Book any VIP table or tour this weekend and save 20%. Use code SAPLUG20 at checkout. Limited availability.",
      imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800",
      type: "banner",
      targetAll: true,
      active: true,
      startsAt: new Date("2026-06-06"),
      endsAt: new Date("2026-07-31"),
    },
    {
      title: "New Member Welcome Bonus",
      body: "Sign up today and receive R200 credit toward your first booking. Valid for 30 days.",
      imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800",
      type: "banner",
      targetAll: true,
      active: true,
    },
  ]).onConflictDoNothing().returning();
  console.log("✓ promotions");

  console.log("\n✅ Database seeded successfully!");
  console.log("The app now has real SA nightlife content to display.");
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
