// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sa-plug/App.tsx": () => import("../components/mockups/sa-plug/App.tsx"),
  "./components/mockups/sa-plug/CheckoutConfirmed.tsx": () => import("../components/mockups/sa-plug/CheckoutConfirmed.tsx"),
  "./components/mockups/sa-plug/CheckoutDetails.tsx": () => import("../components/mockups/sa-plug/CheckoutDetails.tsx"),
  "./components/mockups/sa-plug/CheckoutPayment.tsx": () => import("../components/mockups/sa-plug/CheckoutPayment.tsx"),
  "./components/mockups/sa-plug/ClubDetail.tsx": () => import("../components/mockups/sa-plug/ClubDetail.tsx"),
  "./components/mockups/sa-plug/Clubs.tsx": () => import("../components/mockups/sa-plug/Clubs.tsx"),
  "./components/mockups/sa-plug/CountryCodePicker.tsx": () => import("../components/mockups/sa-plug/CountryCodePicker.tsx"),
  "./components/mockups/sa-plug/Dining.tsx": () => import("../components/mockups/sa-plug/Dining.tsx"),
  "./components/mockups/sa-plug/ForgotPassword.tsx": () => import("../components/mockups/sa-plug/ForgotPassword.tsx"),
  "./components/mockups/sa-plug/Home.tsx": () => import("../components/mockups/sa-plug/Home.tsx"),
  "./components/mockups/sa-plug/OTPVerify.tsx": () => import("../components/mockups/sa-plug/OTPVerify.tsx"),
  "./components/mockups/sa-plug/Onboarding.tsx": () => import("../components/mockups/sa-plug/Onboarding.tsx"),
  "./components/mockups/sa-plug/Profile.tsx": () => import("../components/mockups/sa-plug/Profile.tsx"),
  "./components/mockups/sa-plug/Reservations.tsx": () => import("../components/mockups/sa-plug/Reservations.tsx"),
  "./components/mockups/sa-plug/Shop.tsx": () => import("../components/mockups/sa-plug/Shop.tsx"),
  "./components/mockups/sa-plug/SignIn.tsx": () => import("../components/mockups/sa-plug/SignIn.tsx"),
  "./components/mockups/sa-plug/SignUp.tsx": () => import("../components/mockups/sa-plug/SignUp.tsx"),
  "./components/mockups/sa-plug/Splash.tsx": () => import("../components/mockups/sa-plug/Splash.tsx"),
  "./components/mockups/sa-plug/Tours.tsx": () => import("../components/mockups/sa-plug/Tours.tsx"),
  "./components/mockups/sa-plug/Welcome.tsx": () => import("../components/mockups/sa-plug/Welcome.tsx")
};
